version: '3'
services:
  client:
    image: matagaro12/yoloclient_ip2:1.0.0
    ports:
      - 8000:8000
    stdin_open: true
    depends_on:
      - backend
    networks:
      yolo_ip2_network:


volumes:
  mongo_data:

  networks:
  yolo_ip2_network:
      driver: bridge