
---
- name: Yolo Playbook
  hosts: all
  become: true

  tasks:
    - name: Include Install docker role
      include_role:
        name: roles/install-docker 

    - name: Include Clone Repo Role
      include_role:
        name: roles/cloneRepo
     
    - name: Include Create volume role
      include_role:
        name: roles/automationDockerCompose

