
---
- name: Yolo Playbook
  hosts: all
  become: true

  roles: 
    - roles/install-docker 
    - roles/cloneRepo 
    - roles/createVolume
    - roles/createNetwork
    - roles/databaseconfiguration
    - roles/backendConfiguration
    - roles/clientConfiguration