
---
- name: Yolo Playbook
  hosts: all
  become: true
  vars:
    repo: "https://github.com/Thazes/yolo.git"
    dest: "/home/matagaro/yolo"

  roles: 
    - roles/install-git
    - roles/install-docker