
---
- name: Yolo Playbook
  hosts: all
  become: true
  vars:
    repo: "https://github.com/Thazes/yolo.git"
    dest: "/home/matagaro/yolo"
  tasks:
    - name: Install Git
      include_role:
        name: install-git
    
    - name: checkout git repo
      git:
        repo: "{{ repo }}"
        dest: "{{ dest }}"


    - name: Install Docker
      include_role:
        name: install-docker

    - name: Install image and container for the applicaton
      include_role:
        name: docker-compose-tasks