---
# tasks file for backendConfiguration
- name: Create backend container and connect to network
     docker_container:
     name: backend
     image: matagaro12/yolobackend_ip2:v1.0.1
     state: started
     ports: 
      - '5000:5000'
     networks:
      - name: yolo_network