apiVersion: apps/v1
kind: Deployment
metadata:
    name: client-deployment
    labels: 
     app: client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
      - name: yolo-client
        image: matagaro12/yoloclient_ip2:v1.0.3
        ports:
        - containerPort: 3000
        env:
            - name: CLIENT_HOST
              value: "backend"
            - name: CLIENT_PORT
              value: "10000"


---
apiVersion: v1
kind: Service
metadata:
  name: client
spec:
  ports:
    - name: client
      targetPort: 3000
      port: 3000
      protocol: TCP
      nodePort: 30005
  selector:
    app: client
  type: LoadBalancer