---
# tasks file for createNetwork
- name: Create a network with custom IPAM config
     docker_network:
     name: yolo_network
     state: present
     attachable: true
     ipam_config:
      - subnet: 172.23.27.0/24
        gateway: 172.23.27.2
        iprange: 172.23.27.0/26